toy_app/config/routes.rb
Rails.application.routes.draw do
  resources :microposts
  resources :users
  root 'application#hello'
end

toy_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

toy_app/app/models/micropost.rb
class Micropost < ApplicationRecord
		belongs_to :user
		validates :content, length: { maximum: 140 },
							presence: true
end

toy_app/app/models/user.rb
class User < ApplicationRecord
	has_many :microposts
	validates :name, presence: true
	validates :email, presence: true
end

toy_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
	render html: "hello, world!"
  end
end

toy_app/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost criado com sucesso.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :text, :user_id)
    end
end

toy_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuário criado com sucesso!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Usuário editado com sucesso!' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuário apagado com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

toy_app/app/helpers/application_helper.rb
module ApplicationHelper
end

toy_app/app/helpers/microposts_helper.rb
module MicropostsHelper
end

toy_app/app/helpers/users_helper.rb
module UsersHelper
end

toy_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toy App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

toy_app/app/views/microposts/_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> Micropost proibido de ser salvo:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Conteúdo %>
    <%= form.text_field :content, id: :micropost_content %>
  </div>

  <div class="field">
    <%= form.label :Texto %>
    <%= form.text_field :text, id: :micropost_text %>
  </div>

  <div class="field">
    <%= form.label :Id_de_Usuário%> 
    <%= form.number_field :user_id, id: :micropost_user_id %>
  </div>

  <div class="actions">
    <%= form.submit "Criar Micropost" %>
  </div>
<% end %>

toy_app/app/views/microposts/edit.html.erb
<h1>Editar Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Exibir', @micropost %> |
<%= link_to 'Voltar', microposts_path %>

toy_app/app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Conteúdo</th>
      <th>Texto</th>
      <th>Usuário</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.text %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Exibir', micropost %></td>
        <td><%= link_to 'Editar', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Apagar', micropost, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Micropost', new_micropost_path %>

toy_app/app/views/microposts/new.html.erb
<h1>Novo Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Voltar', microposts_path %>

toy_app/app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conteúdo:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @micropost.text %>
</p>

<p>
  <strong>Usuário:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Editar', edit_micropost_path(@micropost) %> |
<%= link_to 'Voltar', microposts_path %>

toy_app/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> Usuário proibido de ser salvo:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit "Criar Usuário" %>
  </div>
<% end %>

toy_app/app/views/users/edit.html.erb
<h1>Editar Usuário</h1>

<%= render 'form', user: @user %>

<%= link_to 'Exibir', @user %> |
<%= link_to 'Voltar', users_path %>

toy_app/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuários</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Exibir', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Apagar', user, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Usuário', new_user_path %>

toy_app/app/views/users/new.html.erb
<h1>Novo Usuário</h1>

<%= render 'form', user: @user %>

<%= link_to 'Voltar', users_path %>

toy_app/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Voltar', users_path %>